// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Saturn.Types;

#nullable disable

namespace Saturn.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260126154627_PublicIDAndUserType")]
    partial class PublicIDAndUserType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Saturn.Types.ToroUser", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AgreedToPush")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AgreedToTerms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GNID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PfSessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PushAgreeTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TermsAgreeTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
